### PR TITLE
Reworking soundness check for workflows

### PR DESCRIPTION
**Pull request by Anabra**
Improving the efficiency of the workflow soundness checking algorithms. We constrained the workflows nets to be free choice Petri nets. This way, the analysis is more feasible.

### CODE REVIEW

**Comment by sdiehl** [comment]
Still a fair amount of test failures in this. I'll review once it's passing the build.

**Comment by buggymcbugfix** [comment]
I will review this once we have the quickcheck tests, as discussed.

**Comment by sdiehl** [comment]
@Anabra Update the Changelog.

**Comment by buggymcbugfix** [comment]
I think you based the `sound-wf-generation` branch on the `soundness` branch? Therefore my comments there apply here. IMO it would be good to delete this branch + PR to avoid confusion and redundancy.

**Comment by Anabra** [comment]
I did base `sound-wf-generation` on `soundness`. I think these two should be separate PRs, would be easier to review. If we merged `soundness` then `sound-wf-generation` would become simple (only the QC tests). However, the mutual dependency would be still an issue.

**Comment by buggymcbugfix** [comment]
We will continue this work on PR #18 and close this one just to avoid unnecessary overhead.

**Pull request closed without merging**
